import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Emmanuel",
      email: "paliemmanuel@gmail.com",
      password: bcrypt.hashSync("12345678"),
      isAdmin: true,
    },
  ],

  products: [
    {
      name: "Work Chair",
      slug: "work-chair",
      category: "furniture",
      image: "/images/workChair.jpg",
      price: 180,
      brand: "Hermes",
      rating: 4.3,
      numReviews: 1,
      countInStock: 1,
      description: "Adjustable Chair",
    },
    {
      name: "Wine kit",
      slug: "wine-kit",
      category: "craft",
      image: "/images/wineKit.jpg",
      price: 155,
      brand: "Mixed",
      rating: 4.3,
      numReviews: 1,
      countInStock: 1,
      description:
        "This kit includes, two carboys, 30 bottles, a corker, a syphon and a hydrometer",
    },
    {
      name: "Work Station",
      slug: "work-station",
      category: "furniture",
      image: "/images/homeOfficeSet.jpg",
      price: 250,
      brand: "Mixed",
      rating: 1,
      numReviews: 8,
      countInStock: 1,
      description:
        "All in one home office set. Adjustable desk, comfortable chair and a phone holder. lightly used",
    },
    {
      name: "DC Snowboard",
      slug: "ns-snowboard",
      category: "winter gear",
      image: "/images/nsSnowboard.jpg",
      price: 280,
      brand: "Never Summer",
      rating: 4.8,
      numReviews: 8,
      countInStock: 1,
      description: "161cm board to enjoy the soft flurries with",
    },
    {
      name: "Work Chair",
      slug: "work-chair2",
      category: "furniture",
      image: "/images/workChair.jpg",
      price: 180,
      brand: "Hermes",
      rating: 4.3,
      numReviews: 1,
      countInStock: 1,
      description: "Adjustable Chair",
    },
    {
      name: "Wine kit",
      slug: "wine-kit2",
      category: "craft",
      image: "/images/wineKit.jpg",
      price: 155,
      brand: "Mixed",
      rating: 4.3,
      numReviews: 1,
      countInStock: 1,
      description:
        "This kit includes, two carboys, 30 bottles, a corker, a syphon and a hydrometer",
    },
    {
      name: "Work Station",
      slug: "work-station2",
      category: "furniture",
      image: "/images/homeOfficeSet.jpg",
      price: 250,
      brand: "Mixed",
      rating: 1,
      numReviews: 8,
      countInStock: 1,
      description:
        "All in one home office set. Adjustable desk, comfortable chair and a phone holder. lightly used",
    },
    {
      name: "DC Snowboard",
      slug: "ns-snowboard2",
      category: "winter gear",
      image: "/images/nsSnowboard.jpg",
      price: 280,
      brand: "Never Summer",
      rating: 4.8,
      numReviews: 8,
      countInStock: 1,
      description: "161cm board to enjoy the soft flurries with",
    },
  ],
};

export default data;
